version: "3"

services:

  # SA-MP Server
  samp:
    image: southclaws/sampctl         # Latest sampctl runtime as parent image
    entrypoint: sampctl p run         # Start server
    ports:
      - "7777:7777/udp"               # Expose port 7777 to allow UDP connections form outside container
    volumes:
      - .:/samp                       # Bind mount for directory '.' on host to directory '/samp' in container
    depends_on:
      - samp_db                       # Mark container service 'samp_db' as dependency
    container_name: samp              # Container name

  # MySQL Database
  samp_db:
    image: mysql                        # Latest MySQL runtime as parent image
    command:                            # Disable caching_sha2_password plugin to allow SA-MP server to connect
      --default-authentication-plugin=mysql_native_password
    container_name: samp_db             # Container name, use this as database host to establish connection
    environment:                        # Add environment variables
      MYSQL_ROOT_PASSWORD: root